name: Test

on:
  push:
    branches: [main]
  pull_request:
  schedule:
    - cron: "0 12 * * *"

jobs:
  get-python-versions:
    runs-on: ubuntu-latest
    outputs:
      python-matrix: ${{ steps.get-versions.outputs.latest-python-versions }}
    steps:
      - uses: snok/latest-python-versions@1674eb882567056bdbde1e362db522ed5e4e5124 # v1
        id: get-versions
        with:
          min-version: "3.8"

  test:
    needs: get-python-versions
    strategy:
      fail-fast: false
      matrix:
        python-version: ${{ fromJson(needs.get-python-versions.outputs.python-matrix) }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v6
      - run: uv run --python ${{ matrix.python-version }} pytest

  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v6
      - run: uv run --upgrade ruff check

  ty:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v6
      - run: uv run --upgrade ty check
